### ISSUE TITLE
POST should put data into request body

### ISSUE THREAD

**Issue by v4rakh** [tasoskakour/react-use-oauth2#12]
Hi, thanks for maintaining this library @tasoskakour .

Quick question, maybe I am also doing it wrong, but I wonder why `exchangeCodeForTokenServerURL` is getting called with GET query parameters, when `exchangeCodeForTokenMethod` is explicitly set to `POST`. I think this is not correct, it should be given as request body to the `POST` request or make it configurable how the actual payload is getting send (https://github.com/tasoskakour/react-use-oauth2/blob/master/src/components/use-oauth2.ts#L119).

At least [goauthentik](https://goauthentik.io/) doesn't support GET, but POST expects the content to be in body and not in query parameters. Cross-checked doing it in Postman and it worked.

So something like this in the `useOAuth` hook:

```tsx
const exchangeCodeForTokenUseBody = responseType === 'code' && props.exchangeCodeForTokenUseBody; // bool

// ....
if (responseType === 'code' && exchangeCodeForTokenServerURL) {
	let response;

	if (exchangeCodeForTokenUseBody) {
		response = await fetch(exchangeCodeForTokenServerURL, {
			headers: {
				'Content-Type': 'application/x-www-form-urlencoded'
			},
			method: exchangeCodeForTokenMethod || DEFAULT_EXCHANGE_CODE_FOR_TOKEN_METHOD,
			body: new URLSearchParams({
				client_id: clientId,
				grant_type: 'authorization_code',
				code: payload?.code,
				redirect_uri: redirectUri
			})
		});
	} else {
		response = await fetch(
			formatExchangeCodeForTokenServerURL(
				exchangeCodeForTokenServerURL,
				clientId,
				payload?.code,
				redirectUri,
				state
			),
			{
				method: exchangeCodeForTokenMethod || DEFAULT_EXCHANGE_CODE_FOR_TOKEN_METHOD
			}
		);
	}
	payload = await response.json();
}

// ....
```

**Comment by tasoskakour** [comment]
Hi @v4rakh thanks for bringing this up! 

To be honest I'd like this library to be as simple as possible. 

An introduction of a new prop like `exchangeCodeForTokenUseBody` could be a solution to what you describing, or maybe a custom `fetch` function passed as a prop would give even more flexibility to the users of this library. 

When I find some free time, I'll investigate on how we could proceed with this, in the meantime feel free to open any PR that you mind find useful.

Cheers :muscle:

**Comment by ofgi-itsupport** [comment]
+1. Keycloak will give errors unless the parameters are given in the POST body. They cannot be provided as query parameters in the URL.

**Comment by cubikca** [comment]
Further to my comment above, I have put in several hours trying to implement the change provided above. I am currently in npm link hell. As much as I would like to use this library, I am not capable of making the required change in the context of the NPM package, and I cannot use it because Keycloak will not accept this incorrectly formatted request.

**Comment by tasoskakour** [comment]
Thanks for the feedback guys! 

FYI, I'm already working on a solution at this PR: https://github.com/tasoskakour/react-use-oauth2/pull/101 in order to make `exchangeCodeForToken` query fully customizable so you'll be able to shape it however it fit your needs.

I estimate that the new release will be ready in 1-2 days. :+1:

**Comment by tasoskakour** [comment]
Hello everyone! :wave: 

:tada:  You can now use version **v2.0.0** where you can utilize a new property named `exchangeCodeForTokenQueryFn` in order to take full control over how you send the query to your backend. 

Please check here for **instructions**: [exchangeCodeForTokenQueryFn](https://github.com/tasoskakour/react-use-oauth2?tab=readme-ov-file#example-with-exchangecodefortokenqueryfn)

Basically, you will be able to do something like: 
```
const { ... } = useOAuth2({
      // ...
      // Instead of exchangeCodeForTokenQuery (e.g sending form-urlencoded or similar)...
      exchangeCodeForTokenQueryFn: async (callbackParameters) => {
        const formBody = [];
        for (const key in callbackParameters) {
          formBody.push(
            `${encodeURIComponent(key)}=${encodeURIComponent(callbackParameters[key])}`
          );
        }
        const response = await fetch(`YOUR_BACKEND_URL`, {
          method: 'POST',
          body: formBody.join('&'),
          headers: {
            'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8',
          },
        });
        if (!response.ok) throw new Error('Failed');
        const tokenData = await response.json();
        return tokenData;
      },.
      // ...
    })
```
